version: '3.8'

services:
  app:
    container_name: deskito-app
    build:
      dockerfile: ci/Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
      - "${HMR_PORT}:24678"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    command: pnpm dev
    platform: linux/amd64
    networks:
      - deskito

networks:
  deskito:
    external: true