FROM node:21.6.1-alpine as builder
WORKDIR /project


COPY ./ /app

ENV NODE_ENV 'prod'

WORKDIR /app
RUN npm i -g pnpm
RUN pnpm i --prod
RUN pnpm build

FROM nginx:1.25.3
EXPOSE 80
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/nginx.conf /etc/nginx/sites-available/default
COPY --from=builder /app/dist /project/dist